server:
  http_listen_port: 3100
  log_level: warn

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  filesystem:
    directory: /var/loki
compactor:
  working_directory: /var/loki/compactor
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
