name: Governance Integrity

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  run-integrity-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute governance integrity checks
        run: |
          python -m nova.governance.integrity_check --config config/governance/integrity_config.json --reports-dir reports

      - name: Upload governance integrity artifacts
        uses: actions/upload-artifact@v4
        with:
          name: governance-integrity-report
          path: |
            reports/governance_integrity.json
            reports/governance_integrity.md
