name: GPU Integration Checks

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  dgx-readiness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run DGX audit simulation
        run: python -m nova setup --dgx-check
      - name: Targeted integration tests
        run: pytest -k "dgx_audit or container_manager or optimizer or backup_recovery"
